app/pyposeweb/__init__.py
from flask import Blueprint

pypw = Blueprint("pyposeweb", __name__)

from .views import *

app/pyposeweb/views.py
# 功能模块
import numpy as np
from flask import jsonify, redirect, render_template, request, session, url_for
from jinja2 import TemplateNotFound
from ultralytics import YOLO
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename

from ..pgsql_conn import get_db_connection
from . import pypw


@pypw.route("/")
def index():
    user_info = session.get("user_info")
    return render_template("/home.html", user_info=user_info)

templates/pyposeweb/camera.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../static/img/favicon.ico">
    <link rel="icon" type="image/png" href="../static/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>基于yolov8姿态估计智能web项目</title>
    <link rel="stylesheet" href="../../static/css/cameraPage.css" type="text/css"> -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script type="text/javascript" src="../../static/js/cameraPage.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://d3js.org/d3.v6.min.js"></script>
    <link href="https://pic.imgdb.cn/item/6216cb832ab3f51d911e24b6.png" rel="shortcut icon">
    <!--  调用tfjs API -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.2.0/dist/tf.min.js"></script>
    <!-- 调用JQuery API -->
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,600,800" rel="stylesheet">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Main CSS -->
    <link href="../static/css/main.css" rel="stylesheet" />

    <!-- Animation CSS -->
    <link href="../static/css/vendor/aos.css" rel="stylesheet" />

</head>

<body>
    <nav class="topnav navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('pyposeweb.index') }}"><i
                    class="fas fa-anchor mr-2"></i><strong>回到主页</strong></a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto d-flex align-items-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('pyposeweb_wec.cameraPage') }}">实时姿态估计</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto d-flex align-items-center">
                    <li class="nav-item">
                        <span class="nav-link" href="#">
                            <a class="btn btn-info btn-round shadow"
                                href="https://gitee.com/intelligence-version/py-pose-web" target="_blank">
                                <i class="fas fa-cloud-download-alt"></i> 项目地址
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="cameraPage">
        <div>
            <div class="videoPage">
                <video id="video" width="640" height="480" autoplay></video>
            </div>
            <div class="cameraControls">
                <button id="startButton"  class="btn btn-primary" style="margin-left: 20%;">打开摄像头</button>
                <button id="stopButton"  class="btn btn-primary"style="margin-left: 20%;">关闭摄像头</button>
            </div>
        </div>
        <div id="container1" class="Histogram">
            <canvas id="canvas_pose_camera"></canvas>
        </div>
    </div>
    
    </div>
</body>

</html>

templates/pyposeweb/error.html
<!DOCTYPE html>
<html>

<head>
    <title>Error</title>
</head>

<body>
    <h1>Error occurred</h1>
</body>

</html>

templates/pyposeweb/imgPage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../static/img/favicon.ico">
    <link rel="icon" type="image/png" href="../static/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/css/imagePage.css" type="text/css">
    <title>基于yolov8姿态估计智能web项目</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script type="module" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js">
        import * as d3 from "https://cdn.jsdelivr.net/npm/d3@7/+esm";
    </script>
    <script type="text/javascript" src="../../static/js/imagePage.js"></script>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,600,800" rel="stylesheet">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Main CSS -->
    <link href="../static/css/main.css" rel="stylesheet" />

    <!-- Animation CSS -->
    <link href="../static/css/vendor/aos.css" rel="stylesheet" />

</head>

<body>
    <nav class="topnav navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('pyposeweb.index') }}"><i
                    class="fas fa-anchor mr-2"></i><strong>回到主页</strong></a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto d-flex align-items-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('pyposeweb_imgs.imgPage') }}">图片姿态估计 <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto d-flex align-items-center">
                    <li class="nav-item">
                        <span class="nav-link" href="#">
                            <a class="btn btn-info btn-round shadow"
                                href="https://gitee.com/intelligence-version/py-pose-web" target="_blank">
                                <i class="fas fa-cloud-download-alt"></i> 项目地址
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="imagePage">
        <div class="imageUpload">
            <div id="formFile-container">
                <label for="formFile" class="form-label">选择照片</label>
                <input class="form-control" type="file" id="formFile" accept="image/*" required>
            </div>
            <div id="preview-container">
                <img id="preview" class="img-fluid" alt="图片预览">
            </div>
        </div>
        <div id="container1" class="Histogram">
            <canvas id="canvas_pose"></canvas>
        </div>
    </div>
    <div style="margin-top: 2%;">
        <button type="button" class="btn btn-primary" style="margin-left: 20%;"
            onclick="poseDet()">姿态估计检测</button>
        <!-- <button type="button" class="btn btn-primary" onclick="saveImage()" style="margin-left: 40%;">照片保存</button> -->
    </div>
</body>

</html>

templates/pyposeweb/index.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Books {% endblock %}</h1>
{% for book in books %}
<div class='book'>
    <h3>#{{ book[0] }} - {{ book[1] }} BY {{ book[2] }}</h3>
    <i>
        <p>({{ book[3] }} pages)</p>
    </i>
    <p class='review'>{{ book[4] }}</p>
    <i>
        <p>Added {{ book[5] }}</p>
    </i>
</div>
{% endfor %}
{% endblock %}

templates/pyposeweb/videoPage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../static/img/favicon.ico">
    <link rel="icon" type="image/png" href="../static/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>基于yolov8姿态估计智能web项目</title>
    <link rel="stylesheet" href="../../static/css/imagePage.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script type="text/javascript" src="../../static/js/videoPage.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://d3js.org/d3.v6.min.js"></script>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,600,800" rel="stylesheet">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Main CSS -->
    <link href="../static/css/main.css" rel="stylesheet" />

    <!-- Animation CSS -->
    <link href="../static/css/vendor/aos.css" rel="stylesheet" />

</head>

<body>
    <nav class="topnav navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('pyposeweb.index') }}"><i
                    class="fas fa-anchor mr-2"></i><strong>回到主页</strong></a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto d-flex align-items-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('pyposeweb_video.video_pose') }}">视频姿态估计</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto d-flex align-items-center">
                    <li class="nav-item">
                        <span class="nav-link" href="#">
                            <a class="btn btn-info btn-round shadow"
                                href="https://gitee.com/intelligence-version/py-pose-web" target="_blank">
                                <i class="fas fa-cloud-download-alt"></i> 项目地址
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="imagePage">
        <div class="imageUpload">
            <div id="formFile-container">
                <label for="formFile" class="form-label">选择视频</label>
                <input class="form-control" type="file" id="formFile" name="video_data" accept="video/*" required>
            </div>
            <div id="preview-container">
                <video id="preview" class="img-fluid" controls muted autoplay></video>
            </div>
        </div>
        <div id="container1" class="Histogram">
            <canvas id="canvas_pose_video"></canvas>
        </div>
    </div>
    <div style="margin-top: 2%;">
    </div>
</body>

</html>