app/usermode/__init__.py
# user模块


from flask import Blueprint

user_mode = Blueprint("usermode", __name__)

from .views import *

app/usermode/views.py
# user模块


from flask import abort, redirect, render_template, request, session, url_for
from jinja2 import TemplateNotFound
from werkzeug.security import check_password_hash, generate_password_hash

from ..pgsql_conn import get_db_connection
from . import user_mode


# 注册
@user_mode.route("/register/", methods=("GET", "POST"))
def register():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO users (username, password) VALUES ('{username}', '{password}')"
        )
        conn.commit()
        cur.close()
        conn.close()
        return redirect(url_for("usermode.login"))

    return render_template("usermode/register.html")


# 登录
@user_mode.route("/login", methods=["GET", "POST"])
def login():
    conn = get_db_connection()
    cur = conn.cursor()

    if request.method == "GET":
        return render_template("usermode/login.html")
    username = request.form.get("username")
    password = request.form.get("password")
    cur.execute(
        f"SELECT * FROM users WHERE username='{username}' AND password='{password}'"
    )
    res = cur.fetchall()
    conn.commit()
    cur.close()
    conn.close()
    if res:
        # 验证通过
        session["user_info"] = res[0]
        return redirect(url_for("pyposeweb.index"))

    else:
        return render_template("usermode/login.html", msg="用户名或密码输入错误")


# 用户主页
@user_mode.route("/user_main")
def user_main():
    user_info = session.get("user_info")

    return render_template("usermode/user_main.html", user_info=user_info)


# 修改用户信息
@user_mode.route("/update_userInfo/", methods=("GET", "POST"))
def update_userInfo():
    user_info = session.get("user_info")
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute(
            f"UPDATE users SET username='{username}', password='{password}' WHERE id='{user_info[0]}'"
        )
        conn.commit()
        cur.close()
        conn.close()
        return redirect(url_for("usermode.login"))

    return render_template("usermode/update_userInfo.html", user_info=user_info)


@user_mode.route("/logout")
def logout():
    session.pop("user_info", None)
    return redirect(url_for("usermode.login"))

templates/usermode/login.html
<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="./assets/img/favicon.ico">
<link rel="icon" type="image/png" href="./assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>登录界面</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
	name='viewport' />

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,600,800" rel="stylesheet">

<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
	integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<!-- Main CSS -->
<link href="../../static/css/main.css" rel="stylesheet" />

<!-- Animation CSS -->
<link href="../../static/css/vendor/aos.css" rel="stylesheet" />

</head>
<div class="d-md-flex h-md-100 align-items-center">
	<div class="col-md-6 p-0 bg-indigo h-md-100">
		<div class="text-white d-md-flex align-items-center h-100 p-5 text-center justify-content-center">
			<div class="logoarea pt-5 pb-5">
				<p>
					<i class="fa fa-anchor fa-3x"></i>
				</p>
				<h1 class="mb-0 mt-3 display-4">基于 YOLOv8</h1>
				<h5 class="mb-4 font-weight-light">姿态估计智能 Web 项目<i class="fab fa-sass fa-2x text-cyan"></i></h5>
				<a class="btn btn-outline-white btn-lg btn-round"
					href="https://gitee.com/intelligence-vision/py-pose-web" data-toggle="modal"
					data-target="#modal_newsletter">项目地址</a>
			</div>
		</div>
	</div>
	<div class="col-md-6 p-0 bg-white h-md-100 loginarea">
		<div class="d-md-flex align-items-center h-md-100 p-5 justify-content-center">
			<form class="border rounded p-5" method="post">
				<h3 class="mb-4 text-center">登录</h3>
				<div class="form-group">
					<input type="username" name="username" class="form-control" id="exampleInputEmail1"
						aria-describedby="emailHelp" placeholder="请输入用户名" required="">
				</div>
				<div class="form-group">
					<input type="password" name="password" class="form-control" id="exampleInputPassword1"
						placeholder="请输入密码" required="">
				</div>
				<button type="submit" class="btn btn-success btn-round btn-block shadow-sm">登录</button>
				{{msg}}
				<small class="d-block mt-4 text-center"><a class="text-gray"
						href="{{ url_for('usermode.register') }}">还没有账号？立刻注册</a></small>
			</form>
		</div>
	</div>
</div>

</html>

templates/usermode/register.html
<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="./assets/img/favicon.ico">
<link rel="icon" type="image/png" href="./assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>注册界面</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
	name='viewport' />

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,600,800" rel="stylesheet">

<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
	integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<!-- Main CSS -->
<link href="../../static/css/main.css" rel="stylesheet" />

<!-- Animation CSS -->
<link href="../../static/css/vendor/aos.css" rel="stylesheet" />

</head>
<div class="d-md-flex h-md-100 align-items-center">
	<div class="col-md-6 p-0 bg-indigo h-md-100">
		<div class="text-white d-md-flex align-items-center h-100 p-5 text-center justify-content-center">
			<div class="logoarea pt-5 pb-5">
				<p>
					<i class="fa fa-anchor fa-3x"></i>
				</p>
				<h1 class="mb-0 mt-3 display-4">基于 YOLOv8</h1>
				<h5 class="mb-4 font-weight-light">姿态估计智能 Web 项目<i class="fab fa-sass fa-2x text-cyan"></i></h5>
				<a class="btn btn-outline-white btn-lg btn-round"
					href="https://gitee.com/intelligence-vision/py-pose-web" data-toggle="modal"
					data-target="#modal_newsletter">项目地址</a>
			</div>
		</div>
	</div>
	<div class="col-md-6 p-0 bg-white h-md-100 loginarea">
		<div class="d-md-flex align-items-center h-md-100 p-5 justify-content-center">
			<form class="border rounded p-5" method="post">
				<h3 class="mb-4 text-center">注册界面</h3>
				<div class="form-group">
					<input type="username" name="username" class="form-control" id="exampleInputEmail1"
						aria-describedby="emailHelp" placeholder="请输入用户名" required="">
				</div>
				<div class="form-group">
					<input type="password" name="password" class="form-control" id="exampleInputPassword1"
						placeholder="请输入密码" required="">
				</div>
				<button type="submit" class="btn btn-success btn-round btn-block shadow-sm">注册</button>
				<small class="d-block mt-4 text-center"><a class="text-gray"
					href="{{ url_for('usermode.login') }}">已有帐号？立刻登录</a></small>
			</form>
		</div>
	</div>
</div>

</html>

templates/usermode/update_userInfo.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} 用户主页 {% endblock %}</h1>
<div class=''>
    <form method="post">
        <p>
            <label for="username">用户名</label>
            <input type="text" name="username" placeholder="{{ user_info[1] }}">
            </input>
        </p>

        <p>
            <label for="password">密码</label>
            <input type="text" name="password" placeholder="{{ user_info[2] }}">
            </input>
        </p>

        <p>
            <button type="submit">修改</button>
        </p>
    </form>
</div>
{% endblock %}

templates/usermode/user_main.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} 用户主页 {% endblock %}</h1>
<div class=''>
    <h2><a href="{{ url_for('usermode.update_userInfo') }}">修改用户信息</a></h2>
    <div class=''>
        <h3>用户名：{{ user_info[1] }}</h3>
        <h3>密码：{{ user_info[2] }}</h3>
    </div>
</div>
{% endblock %}